---
apiVersion: v1
kind: Service
metadata:
  name: redis-0
  labels:
    app: redis
    node: node0
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node0

---
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis
    node: node1
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node1

---
apiVersion: v1
kind: Service
metadata:
  name: redis-2
  labels:
    app: redis
    node: node2
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node2

---
apiVersion: v1
kind: Service
metadata:
  name: redis-3
  labels:
    app: redis
    node: node3
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node3

---
apiVersion: v1
kind: Service
metadata:
  name: redis-4
  labels:
    app: redis
    node: node4
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node4

---
apiVersion: v1
kind: Service
metadata:
  name: redis-5
  labels:
    app: redis
    node: node5
spec:
  type: LoadBalancer
  ports:
  - name: port-7000
    port: 7000
  - name: port-17000
    port: 17000
  selector:
    app: redis
    node: node5
